### PR TITLE
Fix Subscription cells lookup

### LINKED ISSUE #314: 500 (Internal Server Error) on second Subscription update
**Context**
master branch, images are built locally

**Scenario**
1. Clean database
2. Send the subscription the first time
```
PUT http://localhost:8082/dss/v1/subscriptions/b61a6450-db42-4d0d-91f2-7c1334eda399
{
  "extents": {
    "volume": {
      "outline_polygon": {
        "vertices": [
          { "lng": -91.49723052978516, "lat": 41.70085834502109 },
          { "lng": -91.50341033935547, "lat": 41.6770148220322 },
          { "lng": -91.47989273071289, "lat": 41.67509157220958 },
          { "lng": -91.4663314819336, "lat": 41.69329603398001 },
          { "lng": -91.49723052978516, "lat": 41.70085834502109 }
          ]
      },
      "altitude_upper": {"units": "M", "reference": "W84", "value": 764.79037},
      "altitude_lower": {"units": "M", "reference": "W84", "value": 23.24352}
    },
    "time_start": {"value": "2020-06-03T01:30:00.000Z", "format": "RFC3339"},
    "time_end": {"value": "2020-06-03T22:15:00.000Z", "format": "RFC3339"}
  },
  "old_version": 0,
  "uss_base_url": "http://localhost:12012/services/uss/public/uss/v1/",
  "notify_for_constraints": true
}
```
The server responds with 
```
{
  "constraints": [],
  "operations": [],
  "subscription": {
    "dependent_operations": [],
    "id": "b61a6450-db42-4d0d-91f2-7c1334eda399",
    "implicit_subscription": false,
    "notification_index": 0,
    "notify_for_constraints": true,
    "notify_for_operations": false,
    "time_end": {"format": "RFC3339", "value": "2020-06-03T22:15:00Z"},
    "time_start": {"format": "RFC3339", "value": "2020-06-03T01:30:00Z"},
    "uss_base_url": "http://localhost:12012/services/uss/public/uss/v1/",
    "version": 1
  }
}
```
3. Now we send the update request with a modified time_start (+1h)
```
{
  ...
    "time_start": {"value": "2020-06-03T02:30:00.000Z", "format": "RFC3339"},
  ...
  "old_version": 1,
  ...
}
```
The server responses with `500 Internal Server Error`

Here is the log from dss_sandbox_grpc-backend-for-debugging_1
```
2020-06-02T06:53:42.840Z	info	logging/logging.go:108	Request (/scdpb.UTMAPIUSSDSSAndUSSUSSService/PutSubscription):,,
<,
  extents: <,
    time_end: <,
      format: "RFC3339",
      value: <,
        seconds: 1591222500,
      >,
    >,
    time_start: <,
      format: "RFC3339",
      value: <,
        seconds: 1591151400,
      >,
    >,
    volume: <,
      altitude_lower: <,
        reference: "W84",
        units: "M",
        value: 23.24352,
      >,
      altitude_upper: <,
        reference: "W84",
        units: "M",
        value: 764.79037,
      >,
      outline_polygon: <,
        vertices: <,
          lat: 41.70085834502109,
          lng: -91.49723052978516,,
>,
        vertices: <,
          lat: 41.6770148220322,
          lng: -91.50341033935547,,
>,
        vertices: <,
          lat: 41.67509157220958,
          lng: -91.47989273071289,,
>,
        vertices: <,
          lat: 41.69329603398001,
          lng: -91.4663314819336,,
>,
        vertices: <,
          lat: 41.70085834502109,
          lng: -91.49723052978516,,
>,
      >,
    >,
  >,
  notify_for_constraints: true,
  old_version: 1,
  uss_base_url: "http://0.0.0.0:12012/services/uss/public/uss/v1/",
>,
subscriptionid: "b61a6450-db42-4d0d-91f2-7c1334eda399",
,,
02T06:53:42.845Z	error	zap/server_interceptors.go:39	finished unary call with code Unknown	{"grpc.start_time": "2020-06-02T06:53:42Z", "system": "grpc", "span.kind": "server", "grpc.service": "scdpb.UTMAPIUSSDSSAndUSSUSSService", "grpc.method": "PutSubscription", "peer.address": "172.23.0.2:60752", "error": "sql: Scan error on column index 0, name \"cell_id\": converting driver.Value type int64 (\"-8654677083638726656\") to a uint64: invalid syntax", "grpc.code": "Unknown", "grpc.time_ms": 5.390999794006348},
2020-06-02T06:53:42.845Z	error	errors/errors.go:54	encountered error during unary server call	{"method": "/scdpb.UTMAPIUSSDSSAndUSSUSSService/PutSubscription", "error": "sql: Scan error on column index 0, name \"cell_id\": converting driver.Value type int64 (\"-8654677083638726656\") to a uint64: invalid syntax"},
```

### PR DESCRIPTION
**Pull request by BenjaminPelletier**
This PR fixes #314 by explicitly casting an int64 from the database to a uint64 before constructing an s2.CellID from it.

### CODE REVIEW

File: pkg/scd/store/cockroach/subscriptions.go [hunk 1]
```diff
@@ -70,18 +70,20 @@ func (c *Store) fetchCellsForSubscription(ctx context.Context, q dsssql.Queryabl
...
+		return nil, fmt.Errorf("fetchCellsForSubscription Query error: %s", err)
 	}
 	defer rows.Close()
 
 	var (
-		cu  s2.CellUnion
-		cid s2.CellID
+		cu   s2.CellUnion
+		cidi int64
+		cid  s2.CellID
```
Comment (steeling) [inline pkg/scd/store/cockroach/subscriptions.go:80]: nit can we get rid of this variable?

Comment (BenjaminPelletier) [reply pkg/scd/store/cockroach/subscriptions.go]: Sure; done.
