### PR TITLE
Apply server timeout globally, remove hardcoded datastore timeout

### LINKED ISSUE #1393: DSS continues processing after timeout
Overview:
ANRA observed an instance in which the DSS seemed to continue processing a request even after responding with a timeout code. 

DSS Instance:

- DSS Version (FAA Keysite SDD 1.4)
    - DSS core service version v0.20.0 
    - CockroachDB version v24.1.3 

Events:

The DSS timed out after ~10s while processing a PUT /dss/v1/operational_intent_references/{entityid}/{ovn}
request for the operation: 4748e25c-d3fb-483f-90e2-59568f446e4d 
The request was an attempt to update the state to “Activated”
```
Request Url: https://dss.us.interuss.opensky.dev/dss/v1/operational_intent_references/4748e25c-d3fb-483f-90e2-59568f446e4d/9FI3V7CtbSn5quHEPv5Bn8S8a40LWKYzrFFh8a5QE9A_
Response Exception Status: ProtocolError
Response Duration: 10141.0102 ms
Via: 1.1 google
Date: Thu, 12 Mar 2026 22:04:44 GMT
Exception: The remote server returned an error: (503) Service Unavailable.

upstream connect error or disconnect/reset before headers. reset reason: connection termination
```

The next activate request was made at `Thu Mar 12 2026 22:04:52 GMT`. At this point the DSS despite timing out, completed the request and updated the operation to “Activated” state and assigned a new OVN. 

```
Request Url:
https://dss.us.interuss.opensky.dev/dss/v1/operational_intent_references/4748e25c-d3fb-483f-90e2-59568f446e4d/9FI3V7CtbSn5quHEPv5Bn8S8a40LWKYzrFFh8a5QE9A_
Response Exception Status: ProtocolError
Response Duration: 301.9925 ms
Date: Thu, 12 Mar 2026 22:04:52 GMT 
Via: 1.1 google 
Alt-Svc: h3=":443"; ma=2592000, h3-29=":443"; ma=2592000 
Content-Type: application/json; charset=utf-8 
Content-Length: 193 
Exception: The remote server returned an error: (409) Conflict.

{"message":"Current version is 1larMLymMqUs97vaNL7ZcWhgEVHp1bkr9xCqD-oZHM8_ but client specified version 9FI3V7CtbSn5quHEPv5Bn8S8a40LWKYzrFFh8a5QE9A_ (E:447e9272-9b12-4695-990d-763fb26973ee)"}
```

The response of a POST /dss/v1/operational_intent_references/query proving that the state had already transitioned to Activated
```
Request Url: https://dss.us.interuss.opensky.dev/dss/v1/operational_intent_references/query
Response Code: 200 - OK
Response Duration: 92.4041 ms
Date: Thu, 12 Mar 2026 22:04:47 GMT 
Via: 1.1 google 
Alt-Svc: h3=":443"; ma=2592000, h3-29=":443"; ma=2592000 
Transfer-Encoding: chunked 
Content-Type: application/json; charset=utf-8

-- omitted for brevity --
{"id":"4748e25c-d3fb-483f-90e2-59568f446e4d","manager":"ANRA","uss_availability":"Unknown","version":2,"state":"Activated","ovn":"1larMLymMqUs97vaNL7ZcWhgEVHp1bkr9xCqD-oZHM8_","time_start":{"value":"2026-03-12T22:08:52Z","format":"RFC3339"},"time_end":{"value":"2026-03-12T22:23:41Z","format":"RFC3339"},"uss_base_url":"https://keysite.flyanra.net/flight-auth","subscription_id":"c7eeae0f-4fc2-4e20-aadd-0eb44f01155f"}
-- omitted for brevity --
```

This observation indicates that despite timing out, the DSS continued processing the request.

### PR DESCRIPTION
**Pull request by the-glu**
This PR enforce the value of the timeout flag for all HTTP calls, as it was applied inconsistently through the codebase, especially in SCD where the value was not used at all.

It use an HTTP handle, so it's applied on every call.

There was also another timeout in the code on transactions, hardcoded to 10s. I removed it as it's doesn't seems to make sense anymore with the global timeout (and was also not always applied).

This is potentially disruptive as some slow calls that passed before are now going to be canceled.

This remove a TODO in the code and potentially fix #1393 issue.

### CODE REVIEW

File: pkg/rid/store/datastore/store_test.go [hunk 1]
```diff
@@ -26,7 +26,6 @@ var (
 )
 
 func init() {
```
Comment (mickmis) [inline pkg/rid/store/datastore/store_test.go]: Remove function?
