### PR TITLE
[dss][authorizations] Limit transition to off-nominal states to CMSA role

### LINKED ISSUE #1022: Reject operational intent reference requests to use CMSA states without CMSA scope
**Describe the bug**
A USS without the [`utm.conformance_monitoring_sa` scope](https://github.com/astm-utm/Protocol/blob/d26d3222b9816a5bc90d00287c9746c4255f8f0d/utm.yaml#L2248) (a USS not performing Conformance Monitoring for Situational Awareness) should not be allowed to create or update an operational intent reference to have a CMSA state (Nonconforming, Contingent) per SCD0100:

    A managing USS shall (SCD0100) only transition an operational intent to the Nonconforming and Contingent states if it is also serving the role of CMSA.

Therefore, such a request (to transition to a CMSA state without a CMSA scope) should be rejected.

**To Reproduce**
1. Attempt to transition an operational intent reference to Nonconforming while only providing `utm.strategic_coordination` scope
2. Observe that the attempt succeeds

**Expected behavior**
A request to create or modify an operational intent into a CMSA state (Nonconforming, Contingent) should fail unless `utm.conformance_monitoring_sa` scope is provided in the access token.

### PR DESCRIPTION
**Pull request by barroco**
This PR limit the transition to off-nominal states to managing USS with `Conformance Monitoring for Situational Awareness` role. This should resolve #1022.

Note that the update to interface.gen.go from PR #1023 is required to pass the checks.

Monitoring tests are updated in https://github.com/interuss/monitoring/pull/676.

### CODE REVIEW

File: pkg/auth/auth_test.go [hunk 1]
```diff
@@ -4,6 +4,7 @@ import (
 	"context"
 	"crypto/rand"
 	"crypto/rsa"
+	"github.com/interuss/dss/pkg/api/scdv1"
```
Comment (Shastick) [inline pkg/auth/auth_test.go:7]: Nitpick: github imports are grouped below

File: pkg/scd/operational_intents_handler.go [hunk 2]
```diff
@@ -2,6 +2,7 @@ package scd
 
 import (
 	"context"
+	"github.com/interuss/dss/pkg/auth"
```
Comment (Shastick) [inline pkg/scd/operational_intents_handler.go:5]: Same for imports here

File: pkg/scd/operational_intents_handler.go [hunk 3]
```diff
@@ -384,6 +382,10 @@ func (a *Server) PutOperationalIntentReference(ctx context.Context, manager stri
 	if !state.IsValidInDSS() {
 		return nil, nil, stacktrace.NewErrorWithCode(dsserr.BadRequest, "Invalid OperationalIntent state: %s", params.State)
 	}
+	hasCMSARole := auth.HasScope(authorizedManager.Scopes, restapi.UtmConformanceMonitoringSaScope)
+	if state.IsOffNominal() && !hasCMSARole {
```
Comment (BenjaminPelletier) [inline pkg/scd/operational_intents_handler.go:386]: nit: the thing we want to know here is probably `IsConformanceMonitoringState` or `IsCMSAState` or `RequiresCMSA` rather than `IsOffNominal` (though the logic needs no changes)

File: pkg/scd/operational_intents_handler.go [hunk 4]
```diff
@@ -384,6 +382,10 @@ func (a *Server) PutOperationalIntentReference(ctx context.Context, manager stri
...
+		return nil, nil, stacktrace.NewErrorWithCode(dsserr.PermissionDenied, "Missing `%s` scope to transition to off-nominal state: %s", restapi.UtmConformanceMonitoringSaScope, params.State)
```
Comment (BenjaminPelletier) [inline pkg/scd/operational_intents_handler.go:387]:
```suggestion
		return nil, nil, stacktrace.NewErrorWithCode(dsserr.PermissionDenied, "Missing `%s` Conformance Monitoring for Situational Awareness scope to transition to CMSA state: %s (see SCD0100)", restapi.UtmConformanceMonitoringSaScope, params.State)
```

File: pkg/scd/models/operational_intents.go [hunk 5]
```diff
@@ -56,6 +56,17 @@ func (s OperationalIntentState) IsValidInDSS() bool {
 	return false
 }
 
+// IsOffNominal indicates whether a state is categorized as off-nominal per the standard.
```
Comment (BenjaminPelletier) [inline pkg/scd/models/operational_intents.go:59]: As noted below, I think the information of interest is whether the state is a CMSA state (rather than off-nominal)

**Review by BenjaminPelletier — APPROVED** [review]
