### PR TITLE
Simplify Operations repo interface and fix some Operation behavior

### LINKED ISSUE #344: DSS returning too many Entities on 409'd PUT
**Describe the bug**
I'm PUTing to the operation_references endpoint.  There are two other ops owned by other USSs that intersect my operation.  I supply a valid OVN for only one of those two operations.  I get 409 response as expected.  But I get BOTH operations returned with the 409 response.

**To Reproduce**
1. Submit two operations as USS1
2. Submit one operation as USS2 that intersects both ops from Step 1.
    a. Make sure the operation intesects the other two submitted in Step 1.
    b. Only submit one OVN and let it be valid for one of the existing ops.
3. Receive 409 with both operations in the entity_conflicts array

**Expected behavior**
Given two operations in DSS by another USS
When I submit an operation that intersects both of those operations
And I submit only one valid OVN for those operations
Then I should get a 409
And the entity_conflicts array should contain the operation for the OVN I did not submit

**Additional context**
We may have scripts that reproduce this.  May be able to add stdout to show the issue.

### PR DESCRIPTION
**Pull request by BenjaminPelletier**
This PR primarily simplifies the internal store/repo interface for Operations per #277, and, in the process, incidentally fixes #344, #385, and #391, and partially addresses #386.  An additional adjustment regarding Operations is that DependentSubscriptions is removed from the Subscription model since it was not consistently populated -- instead, this information can be obtained via a separate repo call when needed.  A few tests are augmented, and the validity of end times in the past is clarified in a few cases (ok to query Operations in the past, not ok to create/update an Operation to have its end time in the past).

### CODE REVIEW

File: pkg/scd/errors/errors.go [hunk 1]
```diff
@@ -32,6 +32,16 @@ func MissingOVNsErrorResponse(missingOps []*dssmodels.Operation) (*spb.Status, e
...
 	}
+	for _, missingConstraint := range missingConstraints {
+		constraintRef, err := missingConstraint.ToProto()
+		if err != nil {
+			return nil, stacktrace.Propagate(err, "Error converting missing Constraint to proto")
+		}
+		entityRef := &scdpb.EntityReference{
+			ConstraintReference: constraintRef,
+		}
+		detail.EntityConflicts = append(detail.EntityConflicts, entityRef)
```
Comment (vosst) [inline pkg/scd/errors/errors.go:43]: nit: You could save a temporary here and do:
```
detail.EntityConflicts = append(detail.EntityConflicts, &scdpb.EntityReference{})
```

File: pkg/scd/operations_handler.go [hunk 2]
```diff
@@ -37,17 +34,88 @@ func (a *Server) DeleteOperationReference(ctx context.Context, req *scdpb.Delete
...
+		var subs []*scdmodels.Subscription
+		for _, s := range allsubs {
+			if s.NotifyForOperations {
+				subs = append(subs, s)
+			}
+		}
+
+		// Increment notification indices for Subscriptions to be notified
+		err = incrementNotificationIndices(ctx, r, subs)
+		if err != nil {
```
Comment (vosst) [inline pkg/scd/operations_handler.go:99]: nit: More compact `if err = incrementNotificationIndex; err != nil { ... }`.

File: pkg/scd/operations_handler.go [hunk 3]
```diff
@@ -37,17 +34,88 @@ func (a *Server) DeleteOperationReference(ctx context.Context, req *scdpb.Delete
...
+			return stacktrace.Propagate(err, "Unable to increment notification indices")
+		}
+
+		// Delete Operation from repo
+		err = r.DeleteOperation(ctx, id)
```
Comment (vosst) [inline pkg/scd/operations_handler.go:104]: Same nit here.

File: pkg/scd/server.go [hunk 4]
```diff
@@ -69,3 +71,18 @@ func (a *Server) AuthScopes() map[auth.Operation]auth.KeyClaimedScopesValidator
 func (a *Server) MakeDssReport(ctx context.Context, req *scdpb.MakeDssReportRequest) (*scdpb.ErrorReport, error) {
 	return nil, stacktrace.NewErrorWithCode(dsserr.BadRequest, "Not yet implemented")
 }
+
+func incrementNotificationIndices(ctx context.Context, r repos.Repository, subs []*scdmodels.Subscription) error {
```
Comment (vosst) [inline pkg/scd/server.go:75]: nit: It seems like we want to introduce
```
package models

type Subscriptions []*Subscription

func (subs Subscriptions) IncrementNotificationIndices(context.Context, repos.Repository) error {
  ...
}
```

File: pkg/scd/store/cockroach/operations.go [hunk 5]
```diff
@@ -84,6 +82,13 @@ func (s *repo) fetchOperations(ctx context.Context, q dsssql.Queryable, query st
 		return nil, stacktrace.Propagate(err, "Error in rows query result")
 	}
 
+	for _, op := range payload {
+		err = s.populateOperationCells(ctx, q, op)
```
Comment (vosst) [inline pkg/scd/store/cockroach/operations.go:86]: Same nit for more compactness.

File: pkg/scd/errors/errors.go (hunk 1 above)
Comment (BenjaminPelletier) [reply pkg/scd/errors/errors.go:43]: Done.

File: pkg/scd/operations_handler.go (hunk 2 above)
Comment (BenjaminPelletier) [reply pkg/scd/operations_handler.go:99]: Done.

File: pkg/scd/operations_handler.go (hunk 3 above)
Comment (BenjaminPelletier) [reply pkg/scd/operations_handler.go:104]: Done.

File: pkg/scd/server.go (hunk 4 above)
Comment (BenjaminPelletier) [reply pkg/scd/server.go:75]: Nice :) Done.

File: pkg/scd/store/cockroach/operations.go (hunk 5 above)
Comment (BenjaminPelletier) [reply pkg/scd/store/cockroach/operations.go:86]: Done.

File: pkg/scd/server.go (hunk 4 above)
Comment (BenjaminPelletier) [reply pkg/scd/server.go:75]: Actually, only sort of nice.  Can't define that function in models because repos depends on models and that would create a circular dependency.  So, next best is to put it as a utility function in repos rather than models.  But that also requires the Subscriptions type to be defined there, and that seems like a non-ideal place to define it.  And then, we have to change all the explicit []*scdmodels.Subscription type declarations to the more opaque repos.Subscriptions type.  I'm not sure this actually increases overall clarity.

**Comment by BenjaminPelletier** [comment]
I've converted all the mentioned `err = ...` conversions to single-line if statements, but I think there's a larger conversation to be had here.  There are a very large number of remaining instances in the codebase of two-line `err = ...` + `if err != nil` and we should pick a single preferred style.  I suggest that the primary advantages of the two-line style are:
1) It emphasizes that a statement happens, and then a check occurs -- the fact that an important, possibly-expensive operation is invoked seems more easily lost inside a one-line if statement
2) It is more consistent with the required style when another result other than error is returned -- it doesn't seem ideal to change style just because a return value was added or removed
3) It seems more consistent with the spirit of Go -- [the ternary operator is omitted](https://golang.org/doc/faq#Does_Go_have_a_ternary_form) because clarity is more valuable than brevity

File: pkg/scd/server.go (hunk 4 above)
Comment (vosst) [reply pkg/scd/server.go]: Ah, the circular dependency issue is a deal breaker, indeed.

**Comment by vosst** [comment]
> I've converted all the mentioned `err = ...` conversions to single-line if statements, but I think there's a larger conversation to be had here. There are a very large number of remaining instances in the codebase of two-line `err = ...` + `if err != nil` and we should pick a single preferred style. I suggest that the primary advantages of the two-line style are:
> 
> 1. It emphasizes that a statement happens, and then a check occurs -- the fact that an important, possibly-expensive operation is invoked seems more easily lost inside a one-line if statement
> 2. It is more consistent with the required style when another result other than error is returned -- it doesn't seem ideal to change style just because a return value was added or removed
> 3. It seems more consistent with the spirit of Go -- [the ternary operator is omitted](https://golang.org/doc/faq#Does_Go_have_a_ternary_form) because clarity is more valuable than brevity

I think we should scope variables as tightly as possible as a general guidance, but allow for exceptions. I find https://www.calhoun.io/one-liner-if-statements-with-errors/ to be a good overview, also concluding that it's a case-by-case decision.
